version: "3.9"

services:
  transmission:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/transmission:/config
      - ${MEDIA_DIR}/torrents:/media/torrents
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - PUID=${PUID}
      - GUID=${PGID}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/completed
      - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/media/torrents/watch
    ports:
      - "9091:9091"

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    ports:
      - "7878:7878"

  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/jackett:/config
    ports:
      - "9117:9117"

  plex:
    image: linuxserver/plex
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=${PLEX_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/plex:/config
      - ${MEDIA_DIR}/tv:/media/tv
      - ${MEDIA_DIR}/movies:/media/movies
      - ${MEDIA_DIR}/music:/media/music
    network_mode: "host"
