networks:
  web_lan:
    name: web_lan

services:
  server:
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    networks:
      - web_lan
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      # ---
      - "traefik.http.routers.radarr-lan.entrypoints=web-secure"
      - "traefik.http.routers.radarr-lan.rule=Host(`radarr.${LAN_DOMAIN}`) || Host(`radarr.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.radarr-lan.tls=true"
      - "traefik.http.routers.radarr-lan.tls.certresolver=letsencrypt"
