networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    container_name: prowlarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/prowlarr:/config
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      # ---
      - "traefik.http.routers.prowlarr-lan.entrypoints=web-secure"
      - "traefik.http.routers.prowlarr-lan.rule=Host(`prowlarr.${LAN_DOMAIN}`) || Host(`prowlarr.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.prowlarr-lan.tls=true"
      - "traefik.http.routers.prowlarr-lan.tls.certresolver=letsencrypt"
