version: "3.9"

services:
  minecraft-${SERVER_NAME}:
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/minecraft/${SERVER_NAME}:/config
    environment:
      - EULA=TRUE
      - DIFFICULTY=normal
      - ENABLE_WHITELIST=true
      - SNOOPER_ENABLED=false
      - ALLOW_FLIGHT=true
      - MEMORY=8G
    network_mode: 'host'
