version: "3.9"

services:
  minecraft-kk:
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/minecraft/kk/data:/data
    environment:
      - EULA=TRUE
      - DIFFICULTY=normal
      - ENABLE_WHITELIST=true
      - WHITELIST=${ADMIN_USERNAME}
      - OPS=${ADMIN_USERNAME}
      - SNOOPER_ENABLED=false
      - ALLOW_FLIGHT=true
      - MEMORY=8G
    network_mode: 'host'
