networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: hkotel/mealie
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${APP_DATA_DIR}/mealie:/app/data
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.mealie.loadbalancer.server.port=80"
      # ---
      - "traefik.http.routers.mealie-lan.entrypoints=web-secure"
      - "traefik.http.routers.mealie-lan.rule=Host(`mealie.${LAN_DOMAIN}`) || Host(`mealie.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.mealie-lan.tls=true"
      - "traefik.http.routers.mealie-lan.tls.certresolver=letsencrypt"
