#!/bin/bash

function generateExamples {
    for file in $(find . -maxdepth 1 -type f -name '*.env')
    do
        echo Generating example for: $file
        cat "$file" | cut -d '=' -f 1 | xargs -I "%" echo "%=" > "${file}.example"
    done
}

function default {
    generateExamples
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}