#!/bin/bash

function generate-env-examples {
    for file in $(find . -type f -name '*.env')
    do
        echo Generating example for: $file
        cat "$file" | cut -d '=' -f 1 | xargs -I "%" echo "%=" > "${file}.example"
    done
}

function doco {
    docker-compose \
        -p media-server \
        -f transmission-openvpn/docker-compose.yml \
        -f jackett/docker-compose.yml \
        -f sonarr/docker-compose.yml \
        -f radarr/docker-compose.yml \
        -f plex/docker-compose.yml \
        -f monica/docker-compose.yml \
        $@
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}