networks:
  traefik-docker-socket-proxy: {}

services:
  traefik-docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - traefik-docker-socket-proxy
    environment:
      CONTAINERS: 1
    expose:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik
    restart: unless-stopped
    depends_on:
      - traefik-docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    environment:
      LINODE_TOKEN: ${LINODE_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/traefik:/config
    networks:
      - traefik-docker-socket-proxy
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=DEBUG"
      # -----
      - "--api.dashboard=true"
      # -----
      - "--providers.docker.endpoint=tcp://traefik-docker-socket-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      # -----
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}"
      # -----
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/config/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=linode"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    labels:
      - "traefik.enable=true"
      # -----
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  transmission:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/transmission:/config
      - ${MEDIA_DIR}/torrents:/media/torrents
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - PUID=${PUID}
      - GUID=${PGID}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/completed
      - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/media/torrents/watch
    ports:
      - "9091:9091"

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    ports:
      - "7878:7878"

  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/jackett:/config
    ports:
      - "9117:9117"

  plex:
    image: linuxserver/plex
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=${PLEX_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/plex:/config
      - ${MEDIA_DIR}/tv:/media/tv
      - ${MEDIA_DIR}/movies:/media/movies
      - ${MEDIA_DIR}/music:/media/music
    network_mode: "host"

  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/minecraft/kk/data:/data
    environment:
      - EULA=TRUE
      - DIFFICULTY=normal
      - ENABLE_WHITELIST=true
      - WHITELIST=${MINECRAFT_ADMIN_USERNAME}
      - OPS=${MINECRAFT_ADMIN_USERNAME}
      - SNOOPER_ENABLED=false
      - ALLOW_FLIGHT=true
      - MEMORY=${MINECRAFT_MEMORY}
    network_mode: 'host'