menu:
  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Off
        cmd: poweroff
  - key: "b"
    desc: BitWarden
    submenu:
      - key: "s"
        desc: Select
        submenu:
          - key: "l"
            desc: Login
            cmd: bw-select login
          - key: "c"
            desc: Credit card
            cmd: bw-select card
      - key: "o"
        desc: Open URL
        cmd: bw-open
      - key: "p"
        desc: Paste
        submenu:
          - key: "u"
            desc: Login username
            cmd: bw-get login | jq -r '.data.username' | xargs bw-paste
          - key: "p"
            desc: Login password
            cmd: bw-get login | jq -r '.data.password' | xargs bw-paste
          - key: "t"
            desc: Login TOTP
            cmd: bw-totp | xargs bw-paste
          - key: "n"
            desc: Credit Card Number
            cmd: bw-get card | jq -r '.data.number' | xargs bw-paste
          - key: "e"
            desc: Credit card expiration
            cmd: bw-get card | jq -r '.data.exp_month + .data.exp_year' | xargs bw-paste
          - key: "s"
            desc: Credit card security code
            cmd: bw-get card | jq -r '.data.code' | xargs bw-paste

