networks:
  web_lan:
    name: web_lan

services:
  server:
    image: linuxserver/jackett
    restart: unless-stopped
    container_name: jackett
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/jackett:/config
    networks:
      - web_lan
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.jackett-lan.loadbalancer.server.port=9117"
      # ---
      - "traefik.http.routers.jackett-lan.entrypoints=web-secure"
      - "traefik.http.routers.jackett-lan.rule=Host(`jackett.${LAN_DOMAIN}`) || Host(`jackett.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.jackett-lan.tls=true"
      - "traefik.http.routers.jackett-lan.tls.certresolver=letsencrypt"
