networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/jackett:/config
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      # ---
      - "traefik.http.routers.jackett-lan.entrypoints=web-secure"
      - "traefik.http.routers.jackett-lan.rule=Host(`jackett.${LAN_DOMAIN}`) || Host(`jackett.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.jackett-lan.tls=true"
      - "traefik.http.routers.jackett-lan.tls.certresolver=letsencrypt"
