networks:
  web_lan:
    name: web_lan

services:
  server:
    image: kizaing/kavita
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/komga:/kavita/config
      - ${MEDIA_DIR}/comics:/comics
      - ${MEDIA_DIR}/manga:/manga
      - ${MEDIA_DIR}/books:/books
    networks:
      - web_lan
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      # ---
      - "traefik.http.routers.kavita.entrypoints=web-secure"
      - "traefik.http.routers.kavita.rule=Host(`kavita.${LAN_DOMAIN}`) || Host(`kavita.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.kavita.tls=true"
      - "traefik.http.routers.kavita.tls.certresolver=letsencrypt"
