networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/komga:/kavita/config
      - ${MEDIA_DIR}/comics:/comics
      - ${MEDIA_DIR}/manga:/manga
      - ${MEDIA_DIR}/books:/books
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      # ---
      - "traefik.http.routers.kavita-lan.entrypoints=web-secure"
      - "traefik.http.routers.kavita-lan.rule=Host(`kavita.${LAN_DOMAIN}`) || Host(`kavita.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.kavita-lan.tls=true"
      - "traefik.http.routers.kavita-lan.tls.certresolver=letsencrypt"
