networks:
  service_gateway:
    name: service_gateway

services:
  server:
    build:
      context: "."
    restart: unless-stopped
    volumes:
      - "${APP_DATA_DIR}/foundry:/data"
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      #---
      - "traefik.http.services.foundry.loadbalancer.server.port=30000"
      #---
      - "traefik.http.routers.foundry-lan.entrypoints=web-secure"
      - "traefik.http.routers.foundry-lan.rule=Host(`foundry.${LAN_DOMAIN}`) || Host(`foundry.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.foundry-lan.tls=true"
      - "traefik.http.routers.foundry-lan.tls.certresolver=letsencrypt"
      #---
      - "traefik.http.routers.foundry-wan.entrypoints=proxied-web-secure"
      - "traefik.http.routers.foundry-wan.rule=Host(`foundry.${WAN_DOMAIN}`)"
      - "traefik.http.routers.foundry-wan.tls=true"
      - "traefik.http.routers.foundry-wan.tls.certresolver=letsencrypt"
