networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: docker.io/actualbudget/actual-server:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/actual:/data
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
      - "traefik.http.routers.actual.entrypoints=web-secure"
      - "traefik.http.routers.actual.rule=Host(`actual.${DOMAIN}`)"
