networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.entrypoints=web-secure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
