networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.entrypoints=web-secure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
