networks:
  web_lan:
    name: web_lan

services:
  server:
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    networks:
      - web_lan
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      # ---
      - "traefik.http.routers.sonarr-lan.entrypoints=web-secure"
      - "traefik.http.routers.sonarr-lan.rule=Host(`sonarr.${LAN_DOMAIN}`) || Host(`sonarr.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.sonarr-lan.tls=true"
      - "traefik.http.routers.sonarr-lan.tls.certresolver=letsencrypt"
