networks:
  web_lan:
    name: web_lan
  private: {}

services:
  server:
    image: "photoprism/photoprism"
    depends_on:
      - "database"
    restart: "unless-stopped"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      TZ: "${TZ}"
      PHOTOPRISM_PUID: "${PUID}"
      PHOTOPRISM_PGID: "${PGID}"
      PHOTOPRISM_DATABASE_SERVER: "database"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
    volumes:
      - "${APP_DATA_DIR}/photoprism/storage:/photoprism/storage"
      - "${MEDIA_DIR}/pictures:/photoprism/originals"
    networks:
      - web_lan
      - private
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
      # ---
      - "traefik.http.routers.photoprism-lan.entrypoints=web-secure"
      - "traefik.http.routers.photoprism-lan.rule=Host(`photoprism.${LAN_DOMAIN}`) || Host(`photoprism.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.photoprism-lan.tls=true"
      - "traefik.http.routers.photoprism-lan.tls.certresolver=letsencrypt"

  database:
    image: "mariadb:10.6"
    restart: "unless-stopped"
    environment:
      MARIADB_ROOT_PASSWORD: "photoprism"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "photoprism"
    volumes:
      - "${APP_DATA_DIR}/photoprism/mysql:/var/lib/mysql"
    networks:
      - private
