networks:
  service_gateway:
    name: service_gateway
  private: {}

services:
  server:
    image: traefik
    restart: unless-stopped
    depends_on:
      - docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/traefik:/config
    networks:
      - service_gateway
      - private
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
      # - "8443:8443"
    command:
      - "--log.level=ERROR"
      # ---
      - "--api.dashboard=true"
      # ---
      - "--providers.docker.network=service_gateway"
      - "--providers.docker.endpoint=tcp://docker-socket-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      # ---
      - "--certificatesresolvers.porkbun-le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.porkbun-le.acme.storage=/config/porkbun.acme.json"
      - "--certificatesresolvers.porkbun-le.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.porkbun-le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # ---
      - "--serversTransport.insecureSkipVerify=true"
      # ---
      # - "--traefik.http.middlewares.security-headers.headers.framedeny=true"
      # ---
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http.tls=true"
      - "--entrypoints.web-secure.http.tls.certResolver=porkbun-le"
      - "--entrypoints.web-secure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.web-secure.http.tls.domains[0].sans=*.${DOMAIN}"
      # ---
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # ---
      # - "--entrypoints.proxied-web-secure.address=:8443"
      # - "--entrypoints.proxied-web-secure.http.tls=true"
      # - "--entrypoints.proxied-web-secure.http.tls.certResolver=letsencrypt"
      # - "--entrypoints.proxied-web-secure.http.tls.domains[0].main=${WAN_DOMAIN}"
      # - "--entrypoints.proxied-web-secure.http.tls.domains[0].sans=*.${WAN_DOMAIN}"
      # ---
      # - "--entrypoints.proxied-web.address=:8080"
      # - "--entrypoints.proxied-web.http.redirections.entrypoint.to=proxied-web-secure"
      # - "--entrypoints.proxied-web.http.redirections.entrypoint.scheme=https"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard-lan.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-lan.entrypoints=web-secure"
      - "traefik.http.routers.traefik-dashboard-lan.rule=Host(`traefik.${DOMAIN}`)"

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - private
    environment:
      CONTAINERS: 1
    expose:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
