networks:
  web_lan:
    name: web_lan

services:
  server:
    image: lscr.io/linuxserver/transmission
    restart: unless-stopped
    container_name: transmission
    volumes:
      - ${APP_DATA_DIR}/transmission:/config
      - ${MEDIA_DIR}/torrents:/media/torrents
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    networks:
      - web_lan
    ports:
      - 51413:51413
      - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      # ---
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      # ---
      - "traefik.http.routers.transmission-lan.entrypoints=web-secure"
      - "traefik.http.routers.transmission-lan.rule=Host(`transmission.${LAN_DOMAIN}`) || Host(`transmission.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.transmission-lan.tls=true"
      - "traefik.http.routers.transmission-lan.tls.certresolver=letsencrypt"
