networks:
  web_public:
    name: web_public
  private: {}

services:
  server:
    image: fireflyiii/core
    depends_on:
      - database
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      APP_KEY: "${FIREFLY_APP_KEY}"
      DB_HOST: database
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: firefly
      TRUSTED_PROXIES: "**"
      MAIL_PORT: 2525
    volumes:
      - "${APP_DATA_DIR}/firefly/upload:/var/www/html/storage/upload"
    networks:
      - web_public
      - private
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.rule=Host(`firefly.${DOMAIN}`)"
      - "traefik.http.routers.firefly.tls=true"
      - "traefik.http.routers.firefly.tls.certresolver=letsencrypt"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: firefly
      POSTGRES_USER: firefly
      POSTGRES_PASSWORD: firefly
    volumes:
      - "${APP_DATA_DIR}/firefly/database:/var/lib/postgresql/data"
    networks:
      - private
