services:
  server:
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/minecraft/kk/data:/data
    environment:
      - TZ=${TZ}
      - EULA=TRUE
      - DIFFICULTY=normal
      - ENABLE_WHITELIST=true
      - WHITELIST=${MINECRAFT_ADMIN_USERNAME}
      - OPS=${MINECRAFT_ADMIN_USERNAME}
      - SNOOPER_ENABLED=false
      - ALLOW_FLIGHT=true
      - MEMORY=${MINECRAFT_MEMORY}
    network_mode: "host"
