networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${APP_DATA_DIR}/filebrowser/config:/config"
      - "${APP_DATA_DIR}/filebrowser/database:/database"
      - "${MEDIA_DIR}:/srv"
    networks:
      - service_gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "traefik.http.routers.filebrowser-lan.entrypoints=web-secure"
      - "traefik.http.routers.filebrowser-lan.rule=Host(`filebrowser.${DOMAIN}`)"
