networks:
  service_gateway:
    name: service_gateway

services:
  server:
    image: lscr.io/linuxserver/transmission:4.0.5
    restart: unless-stopped
    container_name: transmission
    volumes:
      - ${APP_DATA_DIR}/transmission:/config
      - ${MEDIA_DIR}/torrents:/media/torrents
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    networks:
      - service_gateway
    ports:
      - 51413:51413
      - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.entrypoints=web-secure"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)"
      - "com.centurylinklabs.watchtower.enable=false"
