networks:
  web_lan:
    name: web_lan

services:
  server:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${APP_DATA_DIR}/filebrowser/config:/config"
      - "${APP_DATA_DIR}/filebrowser/database:/database"
      - "${MEDIA_DIR}:/srv"
    networks:
      - web_lan
    labels:
      - "traefik.enable=true"
      #---
      - "traefik.http.services.filebrowser-lan.loadbalancer.server.port=80"
      #---
      - "traefik.http.routers.filebrowser-lan.entrypoints=web-secure"
      - "traefik.http.routers.filebrowser-lan.rule=Host(`filebrowser.${LAN_DOMAIN}`) || Host(`filebrowser.vpn.${LAN_DOMAIN}`)"
      - "traefik.http.routers.filebrowser-lan.tls=true"
      - "traefik.http.routers.filebrowser-lan.tls.certresolver=letsencrypt"
