networks:
  service_gateway:
    name: service_gateway

services:
  server:
    restart: unless-stopped
    image: pihole/pihole
    environment:
      DNSSEC: "true"
    volumes:
      - "${APP_DATA_DIR}/pihole/server:/etc/pihole"
      - "${APP_DATA_DIR}/pihole/dnsmasq:/etc/dnsmasq.d"
    networks:
      - service_gateway
    dns:
      - "127.0.0.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole-lan.entrypoints=web-secure"
      - "traefik.http.routers.pihole-lan.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.middlewares.pihole-admin-redirect.replacepathregex.regex=^/?$$"
      - "traefik.http.middlewares.pihole-admin-redirect.replacepathregex.replacement=/admin"
      - "traefik.http.routers.pihole-lan.middlewares=pihole-admin-redirect@docker"
